INSERT INTO PoliticalParty (PartyCode, PartyName)
VALUES
('AAHP', 'Australian Affordable Housing Party'),
('ABFA', 'Australian Better Families'),
('ACP', 'Australian Conservatives'),
('AFN', 'Australia First Party (NSW) Incorporated'),
('AJP', 'Animal Justice Party'),
('ALA', 'Yellow Vest Australia'),
('ALP', 'Australian Labor Party'), 
('AMHP', 'The Australian Mental Health Party'),
('APEP', 'Australian People''s Party'),
('ARTS', 'The Arts Party'),
('ASP', 'Shooters, Fishers and Farmers Party'),
('AUC', 'Australian Christians'),
('AUD', 'Australian Democrats'),
('AUP', 'Australian Progressives'),
('AWP', 'Australian Workers Party'),
('CA', 'Centre Alliance'),
('CDP', 'Christian Democratic Party (Fred Nile Group)'),
('CEC', 'Citizens Electoral Council of Australia'),
('CLP', 'Country Liberals (Northern Territory)'),
('CLR', 'Country Labor Party'),
('CPP', 'Child Protection Party'),
('CYA', 'Australian Country Party'),
('DHJP', 'Derryn Hinch''s Justice Party'),
('DLP', 'Democratic Labour Party'),
('FACN', 'FRASER ANNING''S CONSERVATIVE NATIONAL PARTY'),
('FLUX', 'VOTEFLUX.ORG | Upgrade Democracy!'),
('FUT', 'Science Party'),
('GAP', 'The Great Australian Party'),
('GRN', 'Australian Greens'),
('GVIC', 'The Australian Greens – Victoria'),
('HMP', 'Help End Marijuana Prohibition (HEMP) Party'),
('ICAN', 'Independents For Climate Action Now'),
('IMO', 'Involuntary Medication Objectors (Vaccination/Fluoride) Party'),
('JLN', 'Jacqui Lambie Network'),
('KAP', 'Katter''s Australian Party (KAP)'),
('LAOL', 'Love Australia or Leave'),
('LDP', 'Liberal Democratic Party'),
('LNP', 'Liberal National Party of Queensland'),
('LP', 'Liberal Party of Australia'),
('NCP', 'Non-Custodial Parents Party (Equal Parenting)'),
('NMP', 'Health Australia Party'),
('NP', 'National Party of Australia'),
('PHON', 'Pauline Hanson''s One Nation'),
('PIR', 'Pirate Party Australia'),
('REAS', 'Reason Australia'),
('RPA', 'Republican Party of Australia'),
('RUA', 'Rise Up Australia Party'),
('SAL', 'Socialist Alliance'),
('SEP', 'Socialist Equality Party'),
('SOL', 'Climate Action! Immigration Action! Accountable Politicians!'),
('SPA', 'Secular Party of Australia'),
('SPP', '#Sustainable Australia'),
('SUN', 'Seniors United Party of Australia'),
('TSBP', 'The Small Business Party'),
('TSSA', 'Tim Storer Independent SA'),
('TTP', 'The Together Party'),
('TWP', 'The Women''s Party'),
('UAP', 'United Australia Party'),
('VEP', 'Voluntary Euthanasia Party'),
('VNS', 'Victorian Socialists'),
('WAP', 'WESTERN AUSTRALIA PARTY'),
('IND', ' independent'),
('AG', 'Australian Greens'),
('NATS', 'National Party of Australia'); 

